number_of_apples = int(input("How many apples would you like to buy?:"))
number_of_oranges = int(input("How many oranges would you like to buy?:"))
apple_amount = int((number_of_apples * 20))
orange_amount = int((number_of_oranges * 25))
total_amount = int(apple_amount + orange_amount)
print (f"The total amount is {total_amount}")